import type { Metadata } from "next";
import "./globals.css";
import Header from "./header";
import { PostProvider } from "@/app/context/PostsContext";
import { Suspense } from "react";
import Loading from "./loading";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body data-theme="winter">
        <Suspense fallback={<Loading />}>
          <PostProvider>
            <Header />
            {children}
          </PostProvider>
        </Suspense>
      </body>
    </html>
  );
}
